apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-appset
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: prod
  template:
    metadata:
      name: '{{name}}-example'
    spec:
      project: default
      source:
        repoURL: https://github.com/your-repo/your-chart-repo.git
        targetRevision: main
        path: helm-chart-path
        helm:
          valuesFiles:
            - base-values.yaml
            - helm-values/{{name}}/values.yaml
      destination:
        server: '{{server}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

